name: build

on:
  push:
    branches: [ main ]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-calculator-android
          path: build/app/outputs/flutter-apk/app-release.apk

#  ios:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.3.4'
#          channel: 'stable'
#      - run: flutter pub get
#      - run: flutter build ipa --release
#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: flutter-calculator-ios
#          path: build/ios/ipa/calculator.ipa

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build windows --release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-calculator-windows
          path: build/windows/runner/Release
